# general settings
name: RepSR_x4_f256b32_Real3w_xt_big
model_type: SRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10
convert_flag: false

# dataset and data loader settings
datasets:
  train:
    name: Real3w
    type: Real3wDataset
    dataroot_gt: /data1/datasets/d_realsr_3w/HR/
    dataroot_lq: /data1/datasets/d_realsr_3w/LR/
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 512  
    patch_size: 128 #194 776 128/512 during training
    use_flip: true
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  # val:
  #   name: Set5
  #   type: PairedImageDataset
  #   dataroot_gt: datasets/Set5/GTmod12
  #   dataroot_lq: datasets/Set5/LRbicx4
  #   io_backend:
  #     type: disk

# network structures
network_g:
  type: RepSR
  num_in_ch: 1
  num_out_ch: 1
  num_feat: 32
  inside_feat: 64
  num_block: 5 #small arch 3 and big for 5
  upscale: 4
  res_scale: 0.1
  img_range: 255.
  rgb_mean: [0.4488, 0.4371, 0.4040]
  xt_flag: true

# path
path:
  pretrain_network_g:  #experiments/204_EDSR_Lx2_f256b32_DIV2K_300k_B16G1_wandb/models/net_g_300000.pth
  strict_load_g: false
  resume_state: ~
  models: /data1/hukunlei/torch-code/BasicSR/RepSR

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  
  # perceptual_opt:
  #   type: PerceptualLoss
  #   layer_weights:
  #     'conv5_4': 1  # before relu
  #   vgg_type: vgg19
  #   use_input_norm: true
  #   range_norm: false
  #   perceptual_weight: 1.0
  #   style_weight: 0
  #   criterion: l1
  
  ssim_opt:
    type: SSIMLoss


# # validation settings
# val:
#   val_freq: !!float 5e3
#   save_img: false

#   metrics:
#     psnr: # metric name, can be arbitrary
#       type: calculate_psnr
#       crop_border: 4
#       test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
