# general settings
name: X2SR_x2_worddata_finetune
model_type: SRModel
scale: 2
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10
gray_mode: true
convert_flag: true

datasets:
  test_1:  # the 1st test dataset
    name: Real3w
    type: Real3wDataset
    dataroot_gt: /data1/hukunlei/X1/word_test_data_new/
    dataroot_lq: /data1/hukunlei/X1/word_test_data_new/
    io_backend:
      type: disk
    need_gt: false

# network structures
network_g:
  type: X2SR
  num_in_ch: 1
  num_out_ch: 1
  num_feat: 16
  inside_feat: 64
  num_block: 3
  upscale: 2
  res_scale: 0.1
  img_range: 255.
  rgb_mean: [0.4488, 0.4371, 0.4040]
  deploy_flag: true

# path
path:
  pretrain_network_g: experiments/X2SR_x2_worddata_finetune/models/net_g_30000.pth
  #pretrain_network_g: experiments/RepSR_x4_f256b32_Real3w_xt/reparam/net_g_1000000_reparam.pth
  strict_load_g: false
  resume_state: ~
  models: /data1/hukunlei/torch-code/BasicSR/RepSR

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true #false
  suffix: finetune 

  # metrics:
  #   psnr: # metric name, can be arbitrary
  #     type: calculate_psnr
  #     crop_border: 4
  #     test_y_channel: false